config/routes.rb
ArtyGeekParty::Application.routes.draw do
  root to: "home#index"

  devise_for :users,  controllers: {sessions: 'sessions'}

  namespace :api, defaults: {format: 'json'}  do
    get '/users/next_birthday' => "users#next_birthday"
    get '/users/current_user' => "users#check_user"
    get '/parties/next_party' => "parties#next_party"
    resources :users, only: [:index]
    resources :parties
  end
end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/party.rb
class Party < ActiveRecord::Base
  belongs_to :user
  default_scope :order => 'date DESC'

  def self.next
      self.all.select { |party| party.date.yday >= Date.today.yday}.sort {|x, y| x.date.yday <=> y.date.yday}.first
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name, :phone, :date_of_birth

  def self.upcoming
    self.all.select { |user| user.date_of_birth.yday > Date.today.yday}.first
  end

  def self.sorted
    upcoming = self.all.select { |user| user.date_of_birth.yday >= Date.today.yday}.sort {|x, y| x.date_of_birth.yday <=> y.date_of_birth.yday}
    next_year = self.all.select { |user| user.date_of_birth.yday < Date.today.yday}.sort {|x, y| x.date_of_birth.yday <=> y.date_of_birth.yday}
    (upcoming << next_year).flatten
  end
end

app/controllers/api/parties_controller.rb
class Api::PartiesController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_action :authenticate_user!, except: :next_party
  before_action :set_party, only: [:show, :edit, :update, :destroy]

  # GET /parties
  def index
    puts current_user.inspect
    @parties = Party.all
    render json: @parties
  end

  def next_party
    @party = Party.next
    render json: @party
  end
  # GET /parties/1
  def show
    render json: @party
  end

  # GET /parties/new
  def new
    @party = Party.new
  end

  # GET /parties/1/edit
  def edit
  end

  # POST /parties
  def create
    @party = Party.new(party_params)

    if @party.save
      render json:  {message: 'Party was successfully saved', type: 'success'}
    else
      render json: { message: 'Party was not saved', type: 'fault'}
    end
  end

  # PATCH/PUT /parties/1
  def update
    if @party.update(party_params)
      render json:  {message: 'Party was successfully updated', type: 'success'}, status: 200
    else
      render json:  {message: 'Party was not updated', type: 'fault'}
    end
  end

  # DELETE /parties/1
  def destroy
    @party.destroy
    render json: {message: 'successfully destroyed', type: 'success'}
  end


  private

    # Use callbacks to share common setup or constraints between actions.
    def set_party
      @party = Party.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def party_params
      params.require(:party).permit(:title, :date, :location)
    end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_action :authenticate_user!, only: :index


  def next_birthday
    @user = User.upcoming
    render json: @user
  end

  def check_user
    render json: {user: current_user} if current_user
    render json: 'You should sign in or sign up before continuing', status: 403 unless current_user
  end

  def index
    @users = User.sorted
    render json: @users
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :null_session
      skip_before_filter :verify_authenticity_token

  before_action :configure_permitted_parameters, if: :devise_controller?
  after_filter  :set_csrf_cookie_for_ng

  def set_csrf_cookie_for_ng
    cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
  end

  protected

  def verified_request?
    form_authenticity_token == request.headers['X-XSRF-TOKEN']

    puts form_authenticity_token == request.headers['X-XSRF-TOKEN']
  end

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :phone, :date_of_birth, :password_confirmation) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :date_of_birth, :phone, :password, :password_confirmation, :current_password) }
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
    skip_before_filter :verify_authenticity_token

  def create
    resource = warden.authenticate!(:scope => resource_name)
    set_flash_message :notice, :signed_in
    sign_in(resource_name, resource)
    respond_to do |format|
      format.json { render :json => 'Success' }
    end
  end

  def destroy # Assumes only JSON requests
    sign_out
    reset_session
    cookies['XSRF-TOKEN'] = form_authenticity_token

    render :json => {
        'csrfToken' => form_authenticity_token
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/home/index.html.haml
%span{ "ng-show" => "global_message" }
  {{global_message}}
.ng-container{"ng-view" => ""}

app/views/layouts/_navigation.html.haml
= link_to "Artygeek Party", root_path, :class => 'brand'

app/views/layouts/application.html.haml
!!!
%html{ "ng-app" => "ArtyParty"}
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Artygeek Party"
      %meta{:content => content_for?(:description) ? yield(:description) : "Artygeek Party", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        //= javascript_include_tag "//ajax.googleapis.com/ajax/libs/angularjs/1.0.6/angular.min.js"
        = javascript_include_tag "http://maps.google.com/maps/api/js?sensor=false"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    .navbar.navbar-fixed-top
      %nav.navbar-inner
        .container{ "ng-include" => "'../assets/header.html'", "ng-controller" => "HeaderController" }

    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = yield
          %footer

      / ! end of .container
    / ! end of #main

app/views/parties/_form.html.haml
= form_for @party do |f|
  - if @party.errors.any?
    #error_explanation
      %h2= "#{pluralize(@party.errors.count, "error")} prohibited this party from being saved:"
      %ul
        - @party.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :date
    = f.date_select :date
  .field
    = f.label :location
    = f.text_field :location
  .actions
    = f.submit 'Save'

app/views/parties/edit.html.haml
%h1 Editing party

= render 'form'

= link_to 'Show', @party
\|
= link_to 'Back', parties_path

app/views/parties/index.html.haml
%h1 Listing parties

%table
  %tr
    %th Title
    %th Date
    %th Location
    %th
    %th
    %th

  - @parties.each do |party|
    %tr
      %td= party.title
      %td= party.date
      %td= party.location
      %td= link_to 'Show', party
      %td= link_to 'Edit', edit_party_path(party)
      %td= link_to 'Destroy', party, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Party', new_party_path

app/views/parties/new.html.haml
%h1 New party

= render 'form'

= link_to 'Back', parties_path

app/views/parties/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @party.title
%p
  %b Date:
  = @party.date
%p
  %b Location:
  = @party.location

= link_to 'Edit', edit_party_path(@party)
\|
= link_to 'Back', parties_path